version: "3"

services:
  mongo_db:
    container_name: mongo_container
    restart: always
    image: mongo:7.0.5
    hostname: mongo
    ports:
      - "27127:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
